name: CD Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write    


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production-env 
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build the project
        run: npm run build
      
      - name: Deploy to Production
        id: deployment
        uses: actions/deploy-pages@v4
