name: CI Development

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Lint HTML files using npx
        run: npx htmlhint src/*.html
      - name: Lint CSS files using npx
        run: npx stylelint styles/*.css

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website using Parcel
        run: parcel build src/*.html

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
